# Generated by Django 4.2.4 on 2023-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'indoor plants'), ('TW', 'Medicinal plants'), ('BW', 'Outdoor Plants'), ('S', 'seeds'), ('F', 'fertilizers')], max_length=2),
        ),
    ]
