# Generated by Django 4.2.4 on 2024-01-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_plantseeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantseeds',
            name='product_image',
            field=models.ImageField(upload_to='Seedsimg'),
        ),
    ]
